### ISSUE TITLE
[1.15.2] End Dimension. Ore does not generate on outer islands, only central island.

### ISSUE THREAD

**Issue by Alex-DryFab** [Squidsword/Ores-Above-Diamonds#4]
Ore does not generate on the outer islands in the End dimension.

**Comment by Squidsword** [comment]
Hey Alex, I've pushed a patch that hopefully fixes the issue. I tested the new code and it seemed to work. Try it out. If it still doesn't work, get back to me again and I'll take another look. Thank you for reporting this issue.
